// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "transaction-service/domain"

	mock "github.com/stretchr/testify/mock"
)

// AccountUsecase is an autogenerated mock type for the AccountUsecase type
type AccountUsecase struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: iin, userID
func (_m *AccountUsecase) CreateAccount(iin string, userID int64) error {
	ret := _m.Called(iin, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(iin, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccount provides a mock function with given fields: iin
func (_m *AccountUsecase) DeleteAccount(iin string) error {
	ret := _m.Called(iin)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(iin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositMoney provides a mock function with given fields: iin, number, balance
func (_m *AccountUsecase) DepositMoney(iin string, number string, balance string) error {
	ret := _m.Called(iin, number, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(iin, number, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountByIIN provides a mock function with given fields: iin
func (_m *AccountUsecase) GetAccountByIIN(iin string) ([]domain.Account, error) {
	ret := _m.Called(iin)

	var r0 []domain.Account
	if rf, ok := ret.Get(0).(func(string) []domain.Account); ok {
		r0 = rf(iin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByNumber provides a mock function with given fields: number
func (_m *AccountUsecase) GetAccountByNumber(number string) (*domain.Account, error) {
	ret := _m.Called(number)

	var r0 *domain.Account
	if rf, ok := ret.Get(0).(func(string) *domain.Account); ok {
		r0 = rf(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByUserID provides a mock function with given fields: userID
func (_m *AccountUsecase) GetAccountByUserID(userID int64) (*domain.Account, error) {
	ret := _m.Called(userID)

	var r0 *domain.Account
	if rf, ok := ret.Get(0).(func(int64) *domain.Account); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAccount provides a mock function with given fields:
func (_m *AccountUsecase) GetAllAccount() ([]domain.Account, error) {
	ret := _m.Called()

	var r0 []domain.Account
	if rf, ok := ret.Get(0).(func() []domain.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferMoney provides a mock function with given fields: senderIIN, recipientIIN, amount
func (_m *AccountUsecase) TransferMoney(senderIIN string, recipientIIN string, amount string) error {
	ret := _m.Called(senderIIN, recipientIIN, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(senderIIN, recipientIIN, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
